/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsapp;

import mathsapp.BasicIntegFormGUI;
import mathsapp.FormulaGUI;
import mathsapp.HomePageGUI;
import mathsapp.IndefiniteIntegralGUI;
import mathsapp.IntBySub;

/**
 *
 * @author x14110890
 */
public class CalculusGUI extends javax.swing.JFrame {

    /**
     * Creates new form Formula
     */
    public CalculusGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        LogoLbl = new javax.swing.JLabel();
        CalculusLbl = new javax.swing.JLabel();
        IndefiniteIntegralsBtn = new javax.swing.JButton();
        BasicIntegrationFormulaBtn = new javax.swing.JButton();
        IntegrationBySubstitutionBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        HomeBtn = new javax.swing.JButton();
        BackgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/purple logo.JPG"))); // NOI18N
        LogoLbl.setText("jLabel1");
        getContentPane().add(LogoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 70));

        CalculusLbl.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        CalculusLbl.setForeground(new java.awt.Color(102, 102, 255));
        CalculusLbl.setText("Calculus");
        getContentPane().add(CalculusLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 130, 40));

        IndefiniteIntegralsBtn.setBackground(new java.awt.Color(255, 255, 204));
        IndefiniteIntegralsBtn.setFont(new java.awt.Font("Thonburi", 3, 18)); // NOI18N
        IndefiniteIntegralsBtn.setForeground(new java.awt.Color(102, 102, 255));
        IndefiniteIntegralsBtn.setText("Indefinite Integrals");
        IndefiniteIntegralsBtn.setMaximumSize(new java.awt.Dimension(177, 33));
        IndefiniteIntegralsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndefiniteIntegralsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(IndefiniteIntegralsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, 40));

        BasicIntegrationFormulaBtn.setBackground(new java.awt.Color(255, 255, 204));
        BasicIntegrationFormulaBtn.setFont(new java.awt.Font("Thonburi", 3, 18)); // NOI18N
        BasicIntegrationFormulaBtn.setForeground(new java.awt.Color(102, 102, 255));
        BasicIntegrationFormulaBtn.setText("Basic Integration Formulas");
        BasicIntegrationFormulaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasicIntegrationFormulaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BasicIntegrationFormulaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 40));

        IntegrationBySubstitutionBtn.setBackground(new java.awt.Color(255, 255, 204));
        IntegrationBySubstitutionBtn.setFont(new java.awt.Font("Thonburi", 3, 18)); // NOI18N
        IntegrationBySubstitutionBtn.setForeground(new java.awt.Color(102, 102, 255));
        IntegrationBySubstitutionBtn.setText("Integration By Substitution");
        IntegrationBySubstitutionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntegrationBySubstitutionBtnActionPerformed(evt);
            }
        });
        getContentPane().add(IntegrationBySubstitutionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 40));

        backBtn.setBackground(new java.awt.Color(255, 255, 204));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 40, 40));

        HomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/home.png"))); // NOI18N
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 40, 40));

        BackgroundLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/background.jpg"))); // NOI18N
        BackgroundLbl.setText("property");
        BackgroundLbl.setPreferredSize(new java.awt.Dimension(391, 480));
        getContentPane().add(BackgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 390, 520));

        setSize(new java.awt.Dimension(407, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        HomePageGUI myHomePage = new HomePageGUI();
        myHomePage.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        FormulaGUI myFormula = new FormulaGUI();
        myFormula.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void IndefiniteIntegralsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndefiniteIntegralsBtnActionPerformed
        // TODO add your handling code here:
        IndefiniteIntegralGUI myIndefiniteIntegral = new IndefiniteIntegralGUI();
        myIndefiniteIntegral.setVisible(true);
        dispose();
    }//GEN-LAST:event_IndefiniteIntegralsBtnActionPerformed

    private void BasicIntegrationFormulaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasicIntegrationFormulaBtnActionPerformed
        // TODO add your handling code here:
        BasicIntegFormGUI myBasicIntegForm = new BasicIntegFormGUI();
        myBasicIntegForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_BasicIntegrationFormulaBtnActionPerformed

    private void IntegrationBySubstitutionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntegrationBySubstitutionBtnActionPerformed
        // TODO add your handling code here:
        IntBySub myIntBySub = new IntBySub();
        myIntBySub.setVisible(true);
        dispose();
    }//GEN-LAST:event_IntegrationBySubstitutionBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLbl;
    private javax.swing.JButton BasicIntegrationFormulaBtn;
    private javax.swing.JLabel CalculusLbl;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JButton IndefiniteIntegralsBtn;
    private javax.swing.JButton IntegrationBySubstitutionBtn;
    private javax.swing.JLabel LogoLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
