/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsapp;

/**
 *
 * @author x14428818
 */
public class ConLC1 extends javax.swing.JFrame {

    /**
     * Creates new form Theorems2
     */
    public ConLC1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        Logo1 = new javax.swing.JLabel();
        Home1 = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Construction6 = new javax.swing.JButton();
        Construction7 = new javax.swing.JButton();
        Construction8 = new javax.swing.JButton();
        Construction9 = new javax.swing.JButton();
        Construction10 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/purple logo.JPG"))); // NOI18N
        Logo1.setText("jLabel1");
        getContentPane().add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 70));

        Home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/home.png"))); // NOI18N
        Home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home1ActionPerformed(evt);
            }
        });
        getContentPane().add(Home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 40, 40));

        Next.setBackground(new java.awt.Color(255, 255, 204));
        Next.setForeground(new java.awt.Color(0, 153, 51));
        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        getContentPane().add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/back.png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 40, 40));

        Construction6.setBackground(new java.awt.Color(255, 255, 204));
        Construction6.setForeground(new java.awt.Color(0, 153, 51));
        Construction6.setText("Construction 6");
        Construction6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Construction6ActionPerformed(evt);
            }
        });
        getContentPane().add(Construction6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 160, 30));

        Construction7.setBackground(new java.awt.Color(255, 255, 204));
        Construction7.setForeground(new java.awt.Color(0, 153, 51));
        Construction7.setText("Construction 7");
        Construction7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Construction7ActionPerformed(evt);
            }
        });
        getContentPane().add(Construction7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 160, 30));

        Construction8.setBackground(new java.awt.Color(255, 255, 204));
        Construction8.setForeground(new java.awt.Color(0, 153, 51));
        Construction8.setText("Construction 8");
        Construction8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Construction8ActionPerformed(evt);
            }
        });
        getContentPane().add(Construction8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 160, 30));

        Construction9.setBackground(new java.awt.Color(255, 255, 204));
        Construction9.setForeground(new java.awt.Color(0, 153, 51));
        Construction9.setText("Construction 9");
        Construction9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Construction9ActionPerformed(evt);
            }
        });
        getContentPane().add(Construction9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 160, 30));

        Construction10.setBackground(new java.awt.Color(255, 255, 204));
        Construction10.setForeground(new java.awt.Color(0, 153, 51));
        Construction10.setText("Construction 10");
        Construction10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Construction10ActionPerformed(evt);
            }
        });
        getContentPane().add(Construction10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 160, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/background.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 391, 480));

        setSize(new java.awt.Dimension(407, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        ConLC2 myConLC2 = new ConLC2();
        myConLC2.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_NextActionPerformed

    private void Home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home1ActionPerformed
        HomePageGUI myHomePageGUI = new HomePageGUI();
        myHomePageGUI.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Home1ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        ConstructionsGUI myConstructions = new ConstructionsGUI();
        myConstructions.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void Construction6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Construction6ActionPerformed
        Construction6 myConstruction6 = new Construction6();
        myConstruction6.setVisible(true);
        dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_Construction6ActionPerformed

    private void Construction8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Construction8ActionPerformed
        Construction8 myConstruction8 = new Construction8();
        myConstruction8.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Construction8ActionPerformed

    private void Construction9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Construction9ActionPerformed
        Construction9 myConstruction9 = new Construction9();
        myConstruction9.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Construction9ActionPerformed

    private void Construction7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Construction7ActionPerformed
        Construction7 myConstruction7 = new Construction7();
        myConstruction7.setVisible(true);
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_Construction7ActionPerformed

    private void Construction10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Construction10ActionPerformed
        Construction10 myConstruction10 = new Construction10();
        myConstruction10.setVisible(true);
        dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_Construction10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConLC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConLC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConLC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConLC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ConLC1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Construction10;
    private javax.swing.JButton Construction6;
    private javax.swing.JButton Construction7;
    private javax.swing.JButton Construction8;
    private javax.swing.JButton Construction9;
    private javax.swing.JButton Home1;
    private javax.swing.JLabel Logo1;
    private javax.swing.JButton Next;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
