/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsapp;

/**
 *
 * @author x14428818
 */
public class ConLC2 extends javax.swing.JFrame {

    /**
     * Creates new form Theorems1
     */
    public ConLC2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo1 = new javax.swing.JLabel();
        Home1 = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Construction11 = new javax.swing.JButton();
        Construction12 = new javax.swing.JButton();
        Construction13 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/purple logo.JPG"))); // NOI18N
        Logo1.setText("jLabel1");
        getContentPane().add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 70));

        Home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/home.png"))); // NOI18N
        Home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home1ActionPerformed(evt);
            }
        });
        getContentPane().add(Home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 40, 40));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/back.png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 40, 40));

        Construction11.setBackground(new java.awt.Color(255, 255, 204));
        Construction11.setForeground(new java.awt.Color(0, 153, 51));
        Construction11.setText("Construction 11");
        Construction11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Construction11ActionPerformed(evt);
            }
        });
        getContentPane().add(Construction11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 160, 30));

        Construction12.setBackground(new java.awt.Color(255, 255, 204));
        Construction12.setForeground(new java.awt.Color(0, 153, 51));
        Construction12.setText("Construction 12");
        Construction12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Construction12ActionPerformed(evt);
            }
        });
        getContentPane().add(Construction12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 160, 30));

        Construction13.setBackground(new java.awt.Color(255, 255, 204));
        Construction13.setForeground(new java.awt.Color(0, 153, 51));
        Construction13.setText("Construction 13");
        Construction13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Construction13ActionPerformed(evt);
            }
        });
        getContentPane().add(Construction13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 160, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/background.jpg"))); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 391, 480));
        Background.getAccessibleContext().setAccessibleName("background");

        setSize(new java.awt.Dimension(407, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home1ActionPerformed
        HomePageGUI myHomePageGUI = new HomePageGUI();
        myHomePageGUI.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Home1ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        ConLC1 myTheopg1 = new ConLC1();
        myTheopg1.setVisible(true);
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void Construction12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Construction12ActionPerformed
        Construction12 myConstruction12 = new Construction12();
        myConstruction12.setVisible(true);
        dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_Construction12ActionPerformed

    private void Construction13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Construction13ActionPerformed
        Construction13 myConstruction13 = new Construction13();
        myConstruction13.setVisible(true);
        dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_Construction13ActionPerformed

    private void Construction11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Construction11ActionPerformed
        Construction11 myConstruction11 = new Construction11();
        myConstruction11.setVisible(true);
        dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_Construction11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConLC2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConLC2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConLC2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConLC2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConLC2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Construction11;
    private javax.swing.JButton Construction12;
    private javax.swing.JButton Construction13;
    private javax.swing.JButton Home1;
    private javax.swing.JLabel Logo1;
    // End of variables declaration//GEN-END:variables
}
