/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mathsapp;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x14428818
 */
public class ConSearch extends javax.swing.JFrame {
    private String name;
   
    
    
    //declare arraylist of question objects
    private final ArrayList <ConstructionsGUI> aList;
    
    public ConSearch() {
        initComponents();
        name = new String();
        
        //create arraylist of Question objects
        aList = new ArrayList<>();
    }

    /**
     * Creates new form Search
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        Search = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Display = new javax.swing.JButton();
        SearchBtm = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/purple logo.JPG"))); // NOI18N
        Logo.setText("jLabel1");
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 70));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/home.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 40, 40));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/back.png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 40, 40));

        Name.setText("Name ");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));
        getContentPane().add(NameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 160, 120, -1));

        Search.setText("Search Constructions");
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        Display.setText("Display");
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });
        getContentPane().add(Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        SearchBtm.setText("Search");
        SearchBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtmActionPerformed(evt);
            }
        });
        getContentPane().add(SearchBtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/background.jpg"))); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 391, 480));

        setSize(new java.awt.Dimension(407, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        HomePageGUI myHomePage = new HomePageGUI();
        myHomePage.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        ConstructionsGUI myConstructions = new ConstructionsGUI ();
        myConstructions.setVisible (true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
     // Get text from TextFields
        name = NameTF.getText();
        
       
        
        
        ConstructionsGUI c = new ConstructionsGUI();
        
        //add contents of textfields to q
        c.setName(name);
        
        //add q to arrayList of Question objects
        aList.add(c);
    }//GEN-LAST:event_AddActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
       for(int i = 0; i < aList.size();i++){
            JOptionPane.showMessageDialog(null, "Name: "+aList.get(i).getName());
       }
    }//GEN-LAST:event_DisplayActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
       NameTF.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
      if (NameTF.getText().equals("")){
          JOptionPane.showMessageDialog(null, "You must enter the construction that you wish to delete");
      }
      else if (aList.isEmpty()){
          JOptionPane.showMessageDialog(null, "Sorry there is nothing to delete");
      }
      else {
          name = NameTF.getText();
          for (int i = 0; i <aList.size(); i++){
              if (aList.get(i).getName().equals(name)){
              aList.remove(i);
              JOptionPane.showMessageDialog(null, "Deleted iteam at index" + i);
              break;
              }
              if (i == aList.size() -1){
                  JOptionPane.showMessageDialog(null,"Sorry that could not be found");
              }
              
          
          }
      }
             
          
    }//GEN-LAST:event_DeleteActionPerformed

    private void SearchBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtmActionPerformed
      String searchType = JOptionPane.showInputDialog(null, "Please enter construction to search for");
        for (ConstructionsGUI aList1 : aList) {
            if (searchType.equalsIgnoreCase(aList1.getName())) {
                JOptionPane.showMessageDialog(null, "Name" + aList1.getName());
            }
        }
    }//GEN-LAST:event_SearchBtmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Back;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Display;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameTF;
    private javax.swing.JLabel Search;
    private javax.swing.JButton SearchBtm;
    private javax.swing.JButton home;
    // End of variables declaration//GEN-END:variables
}
