/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsapp;

import mathsapp.GeoGUI;
import mathsapp.HomePageGUI;
import mathsapp.QuickQuestionGUI;
import mathsapp.TrigGUI;

/**
 *
 * @author x14110890
 */
public class FormulaGUI extends javax.swing.JFrame {

    /**
     * Creates new form Formula
     */
    public FormulaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoLbl = new javax.swing.JLabel();
        formulaeLbl = new javax.swing.JLabel();
        AlgebraBtn = new javax.swing.JButton();
        CalculasBtn = new javax.swing.JButton();
        GeometryBtn = new javax.swing.JButton();
        TrigonometryBtn = new javax.swing.JButton();
        QuickQuestionBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        HomeBtn = new javax.swing.JButton();
        BackgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/purple logo.JPG"))); // NOI18N
        LogoLbl.setText("jLabel1");
        getContentPane().add(LogoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 70));

        formulaeLbl.setFont(new java.awt.Font("Thonburi", 3, 20)); // NOI18N
        formulaeLbl.setForeground(new java.awt.Color(51, 0, 51));
        formulaeLbl.setText("Formulae");
        getContentPane().add(formulaeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 130, 40));

        AlgebraBtn.setBackground(new java.awt.Color(255, 255, 204));
        AlgebraBtn.setFont(new java.awt.Font("Thonburi", 3, 20)); // NOI18N
        AlgebraBtn.setForeground(new java.awt.Color(51, 0, 51));
        AlgebraBtn.setText("Algebra");
        AlgebraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgebraBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AlgebraBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 170, 40));

        CalculasBtn.setBackground(new java.awt.Color(255, 255, 204));
        CalculasBtn.setFont(new java.awt.Font("Thonburi", 3, 20)); // NOI18N
        CalculasBtn.setForeground(new java.awt.Color(51, 0, 51));
        CalculasBtn.setText("Calculus");
        CalculasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculasBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CalculasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 170, 40));

        GeometryBtn.setBackground(new java.awt.Color(255, 255, 204));
        GeometryBtn.setFont(new java.awt.Font("Thonburi", 3, 20)); // NOI18N
        GeometryBtn.setForeground(new java.awt.Color(51, 0, 51));
        GeometryBtn.setText("Geometry");
        GeometryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeometryBtnActionPerformed(evt);
            }
        });
        getContentPane().add(GeometryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 170, 40));

        TrigonometryBtn.setBackground(new java.awt.Color(255, 255, 204));
        TrigonometryBtn.setFont(new java.awt.Font("Thonburi", 3, 20)); // NOI18N
        TrigonometryBtn.setForeground(new java.awt.Color(51, 0, 51));
        TrigonometryBtn.setText("Trigonometry");
        TrigonometryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrigonometryBtnActionPerformed(evt);
            }
        });
        getContentPane().add(TrigonometryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 170, 40));

        QuickQuestionBtn.setForeground(new java.awt.Color(51, 0, 51));
        QuickQuestionBtn.setText("Quick Question");
        QuickQuestionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuickQuestionBtnActionPerformed(evt);
            }
        });
        getContentPane().add(QuickQuestionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 40, 40));

        HomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/home.png"))); // NOI18N
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 40, 40));

        BackgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/background.jpg"))); // NOI18N
        BackgroundLbl.setPreferredSize(new java.awt.Dimension(391, 480));
        getContentPane().add(BackgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 390, 520));

        setSize(new java.awt.Dimension(407, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        HomePageGUI myHomePage = new HomePageGUI();
        myHomePage.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        HomePageGUI myHomePage = new HomePageGUI();
        myHomePage.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void AlgebraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgebraBtnActionPerformed
        // TODO add your handling code here: 
        AlgebraGUI myAlgebra = new AlgebraGUI();
        myAlgebra.setVisible(true);
        dispose();
    }//GEN-LAST:event_AlgebraBtnActionPerformed

    private void CalculasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculasBtnActionPerformed
        // TODO add your handling code here:
        CalculusGUI myCalculus = new CalculusGUI();
        myCalculus.setVisible(true);
        dispose();
    }//GEN-LAST:event_CalculasBtnActionPerformed

    private void GeometryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeometryBtnActionPerformed
        // TODO add your handling code here:
        GeoGUI myGeo = new GeoGUI();
        myGeo.setVisible(true);
        dispose();
    }//GEN-LAST:event_GeometryBtnActionPerformed

    private void QuickQuestionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuickQuestionBtnActionPerformed
        // TODO add your handling code here:
        QuickQuestionGUI myQuickQuestion = new QuickQuestionGUI();
        myQuickQuestion.setVisible(true);
        dispose();
    }//GEN-LAST:event_QuickQuestionBtnActionPerformed

    private void TrigonometryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrigonometryBtnActionPerformed
        // TODO add your handling code here:
        TrigGUI myTrig = new TrigGUI();
        myTrig.setVisible(true);
        dispose();
    }//GEN-LAST:event_TrigonometryBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlgebraBtn;
    private javax.swing.JLabel BackgroundLbl;
    private javax.swing.JButton CalculasBtn;
    private javax.swing.JButton GeometryBtn;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JLabel LogoLbl;
    private javax.swing.JButton QuickQuestionBtn;
    private javax.swing.JButton TrigonometryBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel formulaeLbl;
    // End of variables declaration//GEN-END:variables
}
