/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsapp;

/**
 *
 * @author x13335131
 */
public class HomePageGUI extends javax.swing.JFrame {

    /**
     * Creates new form HomePageGUI
     */
    public HomePageGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        ExamPapersbtn = new javax.swing.JButton();
        Constructionsbtm = new javax.swing.JButton();
        Formulasbtn = new javax.swing.JButton();
        Quizbtn = new javax.swing.JButton();
        backgroundBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/purple logo.JPG"))); // NOI18N
        LogoLbl.setText("jLabel1");
        getContentPane().add(LogoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 70));

        titleLbl.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(102, 0, 102));
        titleLbl.setText("Main Menu");
        getContentPane().add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 110, 40));

        ExamPapersbtn.setBackground(new java.awt.Color(255, 255, 204));
        ExamPapersbtn.setFont(new java.awt.Font("Thonburi", 3, 20)); // NOI18N
        ExamPapersbtn.setForeground(new java.awt.Color(102, 0, 102));
        ExamPapersbtn.setText("Exam papers");
        ExamPapersbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ExamPapersbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamPapersbtnActionPerformed(evt);
            }
        });
        getContentPane().add(ExamPapersbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 170, 40));

        Constructionsbtm.setBackground(new java.awt.Color(255, 255, 204));
        Constructionsbtm.setFont(new java.awt.Font("Thonburi", 3, 20)); // NOI18N
        Constructionsbtm.setForeground(new java.awt.Color(102, 0, 102));
        Constructionsbtm.setText("Constructions");
        Constructionsbtm.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Constructionsbtm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Constructionsbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConstructionsbtmActionPerformed(evt);
            }
        });
        getContentPane().add(Constructionsbtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 170, 40));

        Formulasbtn.setBackground(new java.awt.Color(255, 255, 204));
        Formulasbtn.setFont(new java.awt.Font("Thonburi", 3, 20)); // NOI18N
        Formulasbtn.setForeground(new java.awt.Color(102, 0, 102));
        Formulasbtn.setText("Formulae");
        Formulasbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Formulasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormulasbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Formulasbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 170, 40));

        Quizbtn.setBackground(new java.awt.Color(255, 255, 204));
        Quizbtn.setFont(new java.awt.Font("Thonburi", 3, 20)); // NOI18N
        Quizbtn.setForeground(new java.awt.Color(102, 0, 102));
        Quizbtn.setText("Quiz");
        Quizbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Quizbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Quizbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 170, 40));

        backgroundBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/background.jpg"))); // NOI18N
        getContentPane().add(backgroundBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 391, 480));

        setSize(new java.awt.Dimension(407, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExamPapersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamPapersbtnActionPerformed
        ExamCourseGUI myExamLevelsGUI = new ExamCourseGUI();
        myExamLevelsGUI.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_ExamPapersbtnActionPerformed

    private void ConstructionsbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConstructionsbtmActionPerformed
        ConstructionsGUI myConstructionsGUI = new ConstructionsGUI();
        myConstructionsGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_ConstructionsbtmActionPerformed

    private void FormulasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormulasbtnActionPerformed
        FormulaGUI myFormula = new FormulaGUI();
        myFormula.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_FormulasbtnActionPerformed

    private void QuizbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizbtnActionPerformed
        QuizMainGUI myQuizGUI = new QuizMainGUI();
        myQuizGUI.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_QuizbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Constructionsbtm;
    private javax.swing.JButton ExamPapersbtn;
    private javax.swing.JButton Formulasbtn;
    private javax.swing.JLabel LogoLbl;
    private javax.swing.JButton Quizbtn;
    private javax.swing.JLabel backgroundBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
