/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mathsapp;

import javax.swing.JOptionPane;
import mathsapp.HomePageGUI;
import mathsapp.QuizMainGUI;
import mathsapp.highScoreControl;

/**
 *
 * @author x13335131
 */
public class JCLevelQGUI extends javax.swing.JFrame {

    /**
     * Creates new form JCLevel
     */
    public JCLevelQGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LogoLbl = new javax.swing.JLabel();
        getJCHBtn = new javax.swing.JButton();
        getJCOBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        textLbl = new javax.swing.JLabel();
        higherBtn = new javax.swing.JButton();
        ordinaryBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/purple logo.JPG"))); // NOI18N
        LogoLbl.setText("jLabel1");
        jPanel1.add(LogoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 70));

        getJCHBtn.setText("highscores");
        getJCHBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getJCHBtnActionPerformed(evt);
            }
        });
        jPanel1.add(getJCHBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 100, -1));

        getJCOBtn.setText("highscores");
        getJCOBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getJCOBtnActionPerformed(evt);
            }
        });
        jPanel1.add(getJCOBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 330, 110, -1));

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/home.png"))); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 40, 40));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 40, 40));

        textLbl.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        textLbl.setForeground(new java.awt.Color(153, 0, 153));
        textLbl.setText("Please select a level..");
        jPanel1.add(textLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 180, -1));

        higherBtn.setBackground(new java.awt.Color(255, 255, 204));
        higherBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        higherBtn.setForeground(new java.awt.Color(153, 0, 153));
        higherBtn.setText("Higher");
        higherBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        higherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                higherBtnActionPerformed(evt);
            }
        });
        jPanel1.add(higherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 170, 40));

        ordinaryBtn.setBackground(new java.awt.Color(255, 255, 204));
        ordinaryBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ordinaryBtn.setForeground(new java.awt.Color(153, 0, 153));
        ordinaryBtn.setText("Ordinary");
        ordinaryBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ordinaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordinaryBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ordinaryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 170, 40));

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/background.jpg"))); // NOI18N
        jPanel1.add(backgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ordinaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordinaryBtnActionPerformed
        JCOrdQs1GUI myJuniorCertOrd = new JCOrdQs1GUI();
        myJuniorCertOrd.setVisible (true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_ordinaryBtnActionPerformed

    private void higherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_higherBtnActionPerformed
        JCHigherQs1GUI myJuniorCertHigher = new JCHigherQs1GUI();
        myJuniorCertHigher.setVisible (true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_higherBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomePageGUI myHomePage = new HomePageGUI();
        myHomePage.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        QuizMainGUI myQuizGUI = new QuizMainGUI();
        myQuizGUI.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void getJCHBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getJCHBtnActionPerformed
        String test = highScoreControl.getJCHtop5();
        String result = highScoreControl.getJCHtop5();
        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_getJCHBtnActionPerformed

    private void getJCOBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getJCOBtnActionPerformed
        String test = highScoreControl.getJCOtop5();
        String result = highScoreControl.getJCOtop5();
        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_getJCOBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton getJCHBtn;
    private javax.swing.JButton getJCOBtn;
    private javax.swing.JButton higherBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ordinaryBtn;
    private javax.swing.JLabel textLbl;
    // End of variables declaration//GEN-END:variables
}
