/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsapp;

/**
 *
 * @author x13335131
 */
public class JCLevelGUI extends javax.swing.JFrame {

    /**
     * Creates new form JCLevel
     */
    public JCLevelGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VisitBtn = new javax.swing.JButton();
        LogoLbl = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        higherBtn = new javax.swing.JButton();
        ordinaryBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VisitBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VisitBtn.setForeground(new java.awt.Color(0, 153, 255));
        VisitBtn.setText("Save visit history");
        VisitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(VisitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 150, -1));

        LogoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/purple logo.JPG"))); // NOI18N
        LogoLbl.setText("jLabel1");
        jPanel1.add(LogoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 70));

        HomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/home.png"))); // NOI18N
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 40, 40));

        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/back.png"))); // NOI18N
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 40, 40));

        titleLbl.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 153, 255));
        titleLbl.setText("Please select a level..");
        jPanel1.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 180, -1));

        higherBtn.setBackground(new java.awt.Color(255, 255, 204));
        higherBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        higherBtn.setForeground(new java.awt.Color(0, 153, 255));
        higherBtn.setText("Higher");
        higherBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        higherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                higherBtnActionPerformed(evt);
            }
        });
        jPanel1.add(higherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 170, 40));

        ordinaryBtn.setBackground(new java.awt.Color(255, 255, 204));
        ordinaryBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ordinaryBtn.setForeground(new java.awt.Color(0, 153, 255));
        ordinaryBtn.setText("Ordinary");
        ordinaryBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ordinaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordinaryBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ordinaryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 170, 40));

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/background.jpg"))); // NOI18N
        jPanel1.add(backgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(407, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ordinaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordinaryBtnActionPerformed
        JrOLPapersGUI myJrOLPapersGUI = new JrOLPapersGUI();
        myJrOLPapersGUI.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_ordinaryBtnActionPerformed

    private void higherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_higherBtnActionPerformed
        JrHLPapersGUI myJrExamPapersGUI = new JrHLPapersGUI();
        myJrExamPapersGUI.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_higherBtnActionPerformed

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        HomePageGUI myHomePage = new HomePageGUI();
        myHomePage.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        ExamCourseGUI myExamCourseGUI = new ExamCourseGUI();
        myExamCourseGUI.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void VisitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitBtnActionPerformed
        // TODO add your handling code here:
        RecordsGUI myRecordsGUI = new RecordsGUI();
        myRecordsGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_VisitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JLabel LogoLbl;
    private javax.swing.JButton VisitBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton higherBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ordinaryBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
