/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsapp;

import mathsapp.HomePageGUI;
import mathsapp.JuniorCertOrdinaryControl;

/**
 *
 * @author x13335131
 */
public class JCOrdQs1GUI extends javax.swing.JFrame {

    /**
     * Creates new form JuniorCertOrd
     */
    public JCOrdQs1GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        qPicLbl = new javax.swing.JLabel();
        questionLbl = new javax.swing.JLabel();
        opt1 = new javax.swing.JCheckBox();
        opt2 = new javax.swing.JCheckBox();
        nextBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        qPicLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/Q.3.PNG"))); // NOI18N
        qPicLbl.setText("jLabel1");
        jPanel1.add(qPicLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 200, -1));

        questionLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        questionLbl.setText(" U= {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}");
        jPanel1.add(questionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 250, 80));

        question1.add(opt1);
        opt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opt1.setText("    True");
        opt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1ActionPerformed(evt);
            }
        });
        jPanel1.add(opt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 100, 30));

        question1.add(opt2);
        opt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opt2.setText("    False");
        jPanel1.add(opt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 100, 30));

        nextBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nextBtn.setText("next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 90, 30));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 40, 40));

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/home.png"))); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 40, 40));

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/background.jpg"))); // NOI18N
        jPanel1.add(backgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomePageGUI myHomePage = new HomePageGUI();
        myHomePage.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        JCLevelQGUI myJCLevel = new JCLevelQGUI();
        myJCLevel.setVisible(true);
        dispose();
       
    }//GEN-LAST:event_backBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
       String ans="empty" ;
        if (opt1.isSelected()){
            ans="true";
        }else if (opt2.isSelected()){
            ans="false";
        }
        
       JuniorCertOrdinaryControl.populate();
       JuniorCertOrdinaryControl.updateAns(ans, 0);
       JuniorCertOrdinaryControl.validateQuestion1();
       JCOrdQs2GUI JCOQ2 = new JCOrdQs2GUI();
       JCOQ2.setVisible(true);
       dispose();
    }//GEN-LAST:event_nextBtnActionPerformed

    private void opt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt1ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JCheckBox opt1;
    private javax.swing.JCheckBox opt2;
    private javax.swing.JLabel qPicLbl;
    private javax.swing.ButtonGroup question1;
    private javax.swing.JLabel questionLbl;
    // End of variables declaration//GEN-END:variables
}
