/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mathsapp;

import mathsapp.HomePageGUI;

/**
 *
 * @author x13335131
 */
public class LCHigherQs9GUI extends javax.swing.JFrame {

    /**
     * Creates new form LCHigherQs9
     */
    public LCHigherQs9GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        question = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        opt1 = new javax.swing.JCheckBox();
        opt2 = new javax.swing.JCheckBox();
        opt3 = new javax.swing.JCheckBox();
        opt4 = new javax.swing.JCheckBox();
        clearBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        question.setBorder(null);
        question.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        question.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Set A={5,11,8,9,24}\nWhich of the \nfollowing are a sub-set\nof the set A?");
        question.setViewportView(jTextArea1);

        jPanel1.add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 190, -1));

        opt1.setText("{5,11,8,6,9,24}");
        jPanel1.add(opt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        opt2.setText("{5,8}");
        jPanel1.add(opt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        opt3.setText("{9,24,12}");
        jPanel1.add(opt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        opt4.setText("{9,11,8}");
        jPanel1.add(opt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        clearBtn.setText("clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 70, -1));

        nextBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nextBtn.setText("next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 90, 30));

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/home.png"))); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 40, 40));

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/background.jpg"))); // NOI18N
        jPanel1.add(backgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
         int count=0;
         int array[]= new int[4];
         for(int i=0; i<array.length; i++){
             array[i]=0;
         }
         Boolean ans =false;
        if (opt1.isSelected()){
            count++;
            array[0]=1;
        }if (opt2.isSelected()){
            count++;
            array[1]=1;
        }if (opt3.isSelected()){
            count++;
            array[2]=1;
        }if (opt4.isSelected()){
            count++;
            array[3]=1;
        }if (count==2){
              if(array[1]==1){
                 if (array[3]==1){
                     ans=true;
                    
                 }
             }else {
                  ans=false;
              }
        }
            
       
       LeavingCertHigherControl.validateQuestion9(ans);
       LCHigherQs10GUI LCHQ10 = new LCHigherQs10GUI();
       LCHQ10.setVisible(true);
       dispose();
    }//GEN-LAST:event_nextBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomePageGUI myHomePageGUI = new HomePageGUI();
        myHomePageGUI.setVisible (true);
        dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        opt1.setSelected(false);
        opt2.setSelected(false);
        opt3.setSelected(false);
        opt4.setSelected(false);
    }//GEN-LAST:event_clearBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JCheckBox opt1;
    private javax.swing.JCheckBox opt2;
    private javax.swing.JCheckBox opt3;
    private javax.swing.JCheckBox opt4;
    private javax.swing.JScrollPane question;
    // End of variables declaration//GEN-END:variables
}
