/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mathsapp;

import mathsapp.HomePageGUI;

/**
 *
 * @author x13335131
 */
public class LCHigherQs2GUI extends javax.swing.JFrame {

    /**
     * Creates new form LCHigherQs2
     */
    public LCHigherQs2GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        qsPicLbl = new javax.swing.JLabel();
        answerP1Tf = new javax.swing.JTextField();
        answerP2Tf = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        question = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        aLbl = new javax.swing.JLabel();
        bLbl = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        qsPicLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/LCHigherQs2.PNG"))); // NOI18N
        jPanel1.add(qsPicLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 160, 70));

        answerP1Tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        answerP1Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerP1TfActionPerformed(evt);
            }
        });
        jPanel1.add(answerP1Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 50, 40));

        answerP2Tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        answerP2Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerP2TfActionPerformed(evt);
            }
        });
        jPanel1.add(answerP2Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 60, 40));

        clearBtn.setText("clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 70, -1));

        nextBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nextBtn.setText("next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 90, 30));

        question.setBorder(null);
        question.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        question.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Solve this similateous \nequation. \n(please do NOT answer \n  in fraction form)");
        question.setViewportView(jTextArea1);

        jPanel1.add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 190, 120));

        aLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aLbl.setText("A=");
        jPanel1.add(aLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 30, 40));

        bLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bLbl.setText("B=");
        jPanel1.add(bLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/home.png"))); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 40, 40));

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/background.jpg"))); // NOI18N
        jPanel1.add(backgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 391, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
       String a = answerP1Tf.getText();
       String b = answerP2Tf.getText();
       LeavingCertHigherControl.setAnswerQ2(a, b);
       LCHigherQs3GUI LCHQ3 = new LCHigherQs3GUI();
       LCHQ3.setVisible(true);
       dispose();
    }//GEN-LAST:event_nextBtnActionPerformed

    private void answerP1TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerP1TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerP1TfActionPerformed

    private void answerP2TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerP2TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerP2TfActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomePageGUI myHomePageGUI = new HomePageGUI();
        myHomePageGUI.setVisible (true);
        dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        answerP1Tf.setText("");
        answerP2Tf.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aLbl;
    private javax.swing.JTextField answerP1Tf;
    private javax.swing.JTextField answerP2Tf;
    private javax.swing.JLabel bLbl;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel qsPicLbl;
    private javax.swing.JScrollPane question;
    // End of variables declaration//GEN-END:variables
}
