/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsapp;

import java.io.File;

/**
 *
 * @author x14110890
 */
public class LCHLPapersGUI extends javax.swing.JFrame {

    /**
     * Creates new form Year
     */
    public LCHLPapersGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Year = new javax.swing.ButtonGroup();
        LogoLbl = new javax.swing.JLabel();
        title2Lbl = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JButton();
        LcYearLbl = new javax.swing.JLabel();
        j2011 = new javax.swing.JRadioButton();
        j2012 = new javax.swing.JRadioButton();
        j2013 = new javax.swing.JRadioButton();
        backBtn = new javax.swing.JButton();
        BackgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/purple logo.JPG"))); // NOI18N
        LogoLbl.setText("jLabel1");
        getContentPane().add(LogoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 70));

        title2Lbl.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        title2Lbl.setForeground(new java.awt.Color(154, 115, 27));
        title2Lbl.setText("Higher Level");
        getContentPane().add(title2Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 120, 30));

        HomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/home.png"))); // NOI18N
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 40, 40));

        LcYearLbl.setBackground(new java.awt.Color(255, 255, 204));
        LcYearLbl.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        LcYearLbl.setForeground(new java.awt.Color(153, 102, 0));
        LcYearLbl.setText("Snr Exam Papers");
        getContentPane().add(LcYearLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 190, 40));

        Year.add(j2011);
        j2011.setFont(new java.awt.Font("Thonburi", 3, 20)); // NOI18N
        j2011.setForeground(new java.awt.Color(153, 102, 0));
        j2011.setText("2011");
        j2011.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2011ActionPerformed(evt);
            }
        });
        getContentPane().add(j2011, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 110, 40));

        Year.add(j2012);
        j2012.setFont(new java.awt.Font("Thonburi", 3, 20)); // NOI18N
        j2012.setForeground(new java.awt.Color(153, 102, 0));
        j2012.setText("2012");
        j2012.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2012ActionPerformed(evt);
            }
        });
        getContentPane().add(j2012, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 110, 40));

        Year.add(j2013);
        j2013.setFont(new java.awt.Font("Thonburi", 3, 20)); // NOI18N
        j2013.setForeground(new java.awt.Color(153, 102, 0));
        j2013.setText("2013");
        j2013.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2013ActionPerformed(evt);
            }
        });
        getContentPane().add(j2013, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 110, 40));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 40, 40));

        BackgroundLbl.setBackground(new java.awt.Color(255, 255, 204));
        BackgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/background.jpg"))); // NOI18N
        BackgroundLbl.setPreferredSize(new java.awt.Dimension(391, 480));
        getContentPane().add(BackgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 390, 500));

        setSize(new java.awt.Dimension(407, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        HomePageGUI myHomePageGUI = new HomePageGUI();
        myHomePageGUI.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        LCLevelGUI myLCLevelGUI = new LCLevelGUI();
        myLCLevelGUI.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void j2011ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2011ActionPerformed
        // TODO add your handling code here:

        try {
            if ((new File("LCHLP12011.pdf")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler LCHLP12011.pdf");
                p.waitFor();
            } else {
                System.out.println("File does not exist");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_j2011ActionPerformed

    private void j2013ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2013ActionPerformed
        // TODO add your handling code here:
        try {
            if ((new File("LCHLP12013.pdf")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler LCHLP12013.pdf");
                p.waitFor();
            } else {
                System.out.println("File does not exist");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_j2013ActionPerformed

    private void j2012ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2012ActionPerformed
        // TODO add your handling code here:
        try {
            if ((new File("LCHLP12012.pdf")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler LCHLP12012.pdf");
                p.waitFor();
            } else {
                System.out.println("File does not exist");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_j2012ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLbl;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JLabel LcYearLbl;
    private javax.swing.JLabel LogoLbl;
    private javax.swing.ButtonGroup Year;
    private javax.swing.JButton backBtn;
    private javax.swing.JRadioButton j2011;
    private javax.swing.JRadioButton j2012;
    private javax.swing.JRadioButton j2013;
    private javax.swing.JLabel title2Lbl;
    // End of variables declaration//GEN-END:variables
}
