/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mathsapp;

import javax.swing.JOptionPane;
import mathsapp.HomePageGUI;
import mathsapp.highScoreControl;

/**
 *
 * @author x13335131
 */
public class LCLevelQGUI extends javax.swing.JFrame {

    /**
     * Creates new form LCLevel
     */
    public LCLevelQGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoLbl = new javax.swing.JLabel();
        getLCHBtn = new javax.swing.JButton();
        getLCOBtn = new javax.swing.JButton();
        HomeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        textLbl = new javax.swing.JLabel();
        higherBtn = new javax.swing.JButton();
        ordinaryBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/purple logo.JPG"))); // NOI18N
        logoLbl.setText("jLabel1");
        jPanel1.add(logoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 70));

        getLCHBtn.setText("Highscores");
        getLCHBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getLCHBtnActionPerformed(evt);
            }
        });
        jPanel1.add(getLCHBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 100, -1));

        getLCOBtn.setText("highscores");
        getLCOBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getLCOBtnActionPerformed(evt);
            }
        });
        jPanel1.add(getLCOBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 100, -1));

        HomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/home.png"))); // NOI18N
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 40, 40));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 40, 40));

        textLbl.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        textLbl.setForeground(new java.awt.Color(255, 0, 204));
        textLbl.setText("Please select a level..");
        jPanel1.add(textLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 170, 40));

        higherBtn.setBackground(new java.awt.Color(255, 255, 204));
        higherBtn.setFont(new java.awt.Font("Thonburi", 1, 18)); // NOI18N
        higherBtn.setForeground(new java.awt.Color(255, 0, 204));
        higherBtn.setText("Higher");
        higherBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        higherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                higherBtnActionPerformed(evt);
            }
        });
        jPanel1.add(higherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 170, 40));

        ordinaryBtn.setBackground(new java.awt.Color(255, 255, 204));
        ordinaryBtn.setFont(new java.awt.Font("Thonburi", 1, 18)); // NOI18N
        ordinaryBtn.setForeground(new java.awt.Color(255, 0, 204));
        ordinaryBtn.setText("Ordinary");
        ordinaryBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ordinaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordinaryBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ordinaryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 170, 40));

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/background.jpg"))); // NOI18N
        jPanel1.add(backgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void higherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_higherBtnActionPerformed
        LCHigherQs1GUI myLeavingCertHigher = new LCHigherQs1GUI();
        myLeavingCertHigher.setVisible (true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_higherBtnActionPerformed

    private void ordinaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordinaryBtnActionPerformed
        LCOrdQs1GUI myLeavingCertOrd = new LCOrdQs1GUI();
        myLeavingCertOrd.setVisible (true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_ordinaryBtnActionPerformed

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        HomePageGUI myHomePage = new HomePageGUI();
        myHomePage.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        QuizMainGUI myQuizGUI = new QuizMainGUI();
        myQuizGUI.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void getLCHBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getLCHBtnActionPerformed
        String test = highScoreControl.getLCHtop5();
        String result = highScoreControl.getLCHtop5();
        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_getLCHBtnActionPerformed

    private void getLCOBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getLCOBtnActionPerformed
        String test = highScoreControl.getLCOtop5();
        String result = highScoreControl.getLCOtop5();
        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_getLCOBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton getLCHBtn;
    private javax.swing.JButton getLCOBtn;
    private javax.swing.JButton higherBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JButton ordinaryBtn;
    private javax.swing.JLabel textLbl;
    // End of variables declaration//GEN-END:variables
}
