/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author x14110890
 */
package mathsapp;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import mathsapp.HomePageGUI;

//declare QuickQuestion object
public class QuickQuestionGUI extends javax.swing.JFrame {

    private String name, favorite;
    private int mark;
    private int count;

    //declare array of objects
    QuickQuestionC[] arr;

    /**
     * Creates new form Formula
     */
    public QuickQuestionGUI() {
        initComponents();

        //create array
        arr = new QuickQuestionC[20];

        name = new String();
        favorite = new String();
        mark = 0;
        count = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        LogoLbl = new javax.swing.JLabel();
        CalculusLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        HomeBtn = new javax.swing.JButton();
        nameLbl = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        favoriteLbl = new javax.swing.JLabel();
        favoriteTf = new javax.swing.JTextField();
        mark1Lbl = new javax.swing.JLabel();
        mark2 = new javax.swing.JLabel();
        markTf = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        DisplayBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/purple logo.JPG"))); // NOI18N
        LogoLbl.setText("jLabel1");
        getContentPane().add(LogoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 70));

        CalculusLbl.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        CalculusLbl.setForeground(new java.awt.Color(204, 0, 0));
        CalculusLbl.setText("Quick Question");
        getContentPane().add(CalculusLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 180, 40));

        backBtn.setBackground(new java.awt.Color(255, 255, 204));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 40, 40));

        HomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/home.png"))); // NOI18N
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 40, 40));

        nameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLbl.setText("Please Enter Name:");
        getContentPane().add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        nameTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(nameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 140, -1));

        favoriteLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        favoriteLbl.setText("What Is your Favorite Formula:");
        getContentPane().add(favoriteLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        favoriteTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(favoriteTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 140, -1));

        mark1Lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mark1Lbl.setText("Mark Would You Like To ");
        getContentPane().add(mark1Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, 20));

        mark2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mark2.setText("Obtain in Maths:");
        getContentPane().add(mark2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        markTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(markTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 140, -1));

        addBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addBtn.setText("add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 70, -1));

        DisplayBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DisplayBtn.setText("Display");
        DisplayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DisplayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 380, 80, -1));

        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 70, -1));

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        Background.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/background.jpg"))); // NOI18N
        Background.setText("property");
        Background.setPreferredSize(new java.awt.Dimension(391, 480));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 390, 520));

        setSize(new java.awt.Dimension(407, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        HomePageGUI myHomePage = new HomePageGUI();
        myHomePage.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        FormulaGUI myFormula = new FormulaGUI();
        myFormula.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        //declare QQ object
        QuickQuestionC a;

        //create QQ object
        a = new QuickQuestionC();

        // get text from text fields
        name = nameTf.getText();
        favorite = favoriteTf.getText();
        mark = Integer.parseInt(markTf.getText());

        JOptionPane.showMessageDialog(null, "Your Information has been added");

        //adding details to objects
        a.setName(name);
        a.setFavorite(favorite);
        a.setMark(mark);

        //add object to arraylist
        arr[count] = a;
        //increase counter
        count++;
    }//GEN-LAST:event_addBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String searchType = JOptionPane.showInputDialog(null, "Please enter a search type");

        for (int i = 0; i < arr.length; i++) {
            if (searchType.equalsIgnoreCase(arr[i].getName())) {
                JOptionPane.showMessageDialog(null, "Name: " + arr[i].getName() + "\n Favorite " + arr[i].getFavorite() + "\n Mark " + arr[i].getMark());

            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        if (nameTf.getText().equals("") || favoriteTf.getText().equals("") || markTf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Sorry you will need to enter your name, your favorite formula and what mark you would like to delete an object");
        } else if (count == 0) {
            JOptionPane.showMessageDialog(null, "sorry there are no items in the array at present");
        } else {
            name = nameTf.getText();
            favorite = favoriteTf.getText();
            mark = Integer.parseInt(markTf.getText());
            for (int i = 0; i < count; i++) {
                if (arr[i].getName().equals(name) && arr[i].getFavorite().equals(favorite) && arr[i].getMark() == mark) {
                    arr[i] = arr[count - 1];
                    count = count - 1;
                    JOptionPane.showMessageDialog(null, "Delete " + name + ", " + favorite + ", " + mark + " There are now " + count + "items in the array");
                    break;
                }
                if (i == count - 1) {
                    JOptionPane.showMessageDialog(null, "sorry, the items you are looking for could not be found ");
                }

            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void DisplayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBtnActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < arr.length; i++) {
            JOptionPane.showMessageDialog(null, "Name: " + arr[i].getName() + "\n Favorite " + arr[i].getFavorite() + "\n Mark " + arr[i].getMark());

        }
    }//GEN-LAST:event_DisplayBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:File outFile;
        File f;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        //Use a try statement
        try {
            f = new File("QuickQuestion.dat");
            fStream = new FileOutputStream(f);
            oStream = new ObjectOutputStream(fStream);
            //creat objects
            oStream.writeObject(arr);
            oStream.close();
            JOptionPane.showMessageDialog(null, "Your information has been saved ");
        } //catch the IOException
        catch (IOException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CalculusLbl;
    private javax.swing.JButton DisplayBtn;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JLabel LogoLbl;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel favoriteLbl;
    private javax.swing.JTextField favoriteTf;
    private javax.swing.JLabel mark1Lbl;
    private javax.swing.JLabel mark2;
    private javax.swing.JTextField markTf;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTf;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables

    private void setFavorite(String favorite) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setMark(int mark) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String getFavorite() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String getMark() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private QuickQuestionC newQuickQuestionC() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
