/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mathsapp;

/**
 *
 * @author x13335131
 */
public class QuizMainGUI extends javax.swing.JFrame {

    /**
     * Creates new form QuizGUI
     */
    public QuizMainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        logoLbl = new javax.swing.JLabel();
        JuniorCertLbl = new javax.swing.JLabel();
        LCBtn = new javax.swing.JButton();
        JCBtn = new javax.swing.JButton();
        delHighScoresBtn = new javax.swing.JButton();
        resultsBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/home.png"))); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 40, 40));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 40, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/purple logo.JPG"))); // NOI18N
        logoLbl.setText("jLabel1");
        jPanel1.add(logoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 70));

        JuniorCertLbl.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        JuniorCertLbl.setForeground(new java.awt.Color(102, 0, 102));
        JuniorCertLbl.setText("  Quiz page");
        jPanel1.add(JuniorCertLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 130, 40));

        LCBtn.setBackground(new java.awt.Color(255, 255, 204));
        LCBtn.setFont(new java.awt.Font("Thonburi", 3, 20)); // NOI18N
        LCBtn.setForeground(new java.awt.Color(255, 0, 204));
        LCBtn.setText("Leaving Cert");
        LCBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LCBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LCBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 170, 40));

        JCBtn.setBackground(new java.awt.Color(255, 255, 204));
        JCBtn.setFont(new java.awt.Font("Thonburi", 3, 20)); // NOI18N
        JCBtn.setForeground(new java.awt.Color(255, 0, 204));
        JCBtn.setText("Junior Cert");
        JCBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBtnActionPerformed(evt);
            }
        });
        jPanel1.add(JCBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 170, 40));

        delHighScoresBtn.setText("Delete Highscores");
        delHighScoresBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delHighScoresBtnActionPerformed(evt);
            }
        });
        jPanel1.add(delHighScoresBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 140, -1));

        resultsBtn.setText("Previous Results");
        resultsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resultsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 140, -1));

        deleteBtn.setText("Delete previous results");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 180, -1));

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsapp/background.jpg"))); // NOI18N
        jPanel1.add(backgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LCBtnActionPerformed
        LCLevelQGUI myLCLevel = new LCLevelQGUI();
        myLCLevel.setVisible (true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_LCBtnActionPerformed

    private void JCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBtnActionPerformed
        JCLevelQGUI myJCLevel = new JCLevelQGUI();
        myJCLevel.setVisible (true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_JCBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomePageGUI myHomePage = new HomePageGUI();
        myHomePage.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        HomePageGUI myHomePage = new HomePageGUI();
        myHomePage.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void resultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsBtnActionPerformed
        LeavingCertHigherControl.showResults();
        highScoreControl.test();
    }//GEN-LAST:event_resultsBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        LeavingCertHigherControl.deleteResults();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void delHighScoresBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delHighScoresBtnActionPerformed
        highScoreControl.clearHighScores();
    }//GEN-LAST:event_delHighScoresBtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JCBtn;
    private javax.swing.JLabel JuniorCertLbl;
    private javax.swing.JButton LCBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton delHighScoresBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JButton resultsBtn;
    // End of variables declaration//GEN-END:variables
}
